CONTAINER Gvgraph {
    NAME Gvgraph;
    INCLUDE Gvbase;

    GROUP ID_GVPROPERTIES {
        BASETIME ID_GVOPERATOR_GRAPH_TIME_START { }
        BASETIME ID_GVOPERATOR_GRAPH_TIME_END   { }
        LISTVIEW ID_GVOPERATOR_GRAPH_INPUTS { SCALE_H; SCALE_V; }
    }
}