CONTAINER nrprocedural_csvreader {
  GROUP {
    DEFAULT 1;
    STATICTEXT PROCEDURAL_CSVREADER_STATUS { }
  }
  INCLUDE Obaselist;
  GROUP Obaselist {
    DEFAULT 1;

    BOOL       PROCEDURAL_CSVREADER_ENABLED  { DEFAULT 1; }
    PRIORITY   PROCEDURAL_CSVREADER_PRIORITY { }
    SEPARATOR  { LINE; }

    BOOL       PROCEDURAL_CSVREADER_HASHEADER { ANIM OFF; DEFAULT 0; }
    FILENAME   PROCEDURAL_CSVREADER_FILENAME  { ANIM OFF; }

    BOOL       PROCEDURAL_CSVREADER_ANIMATED   { ANIM OFF; DEFAULT 0; PARENTCOLLAPSE; }
    STATICTEXT PROCEDURAL_CSVREADER_ANIMSTATUS { ANIM OFF;            PARENTCOLLAPSE PROCEDURAL_CSVREADER_ANIMATED; }
    BOOL       PROCEDURAL_CSVREADER_ANIMCACHED { ANIM OFF; DEFAULT 0; PARENTCOLLAPSE PROCEDURAL_CSVREADER_ANIMATED; }
    BASETIME   PROCEDURAL_CSVREADER_ANIMOFFSET {                      PARENTCOLLAPSE PROCEDURAL_CSVREADER_ANIMATED; }
    SEPARATOR  { LINE; }

    BUTTON     PROCEDURAL_CSVREADER_ADDENTRY { }
    BUTTON     PROCEDURAL_CSVREADER_SUBENTRY { }
  }
  GROUP PROCEDURAL_CSVREADER_GROUP {
    DEFAULT 1;
  }
}
