#ifndef Toffsetrandomizer_H
#define Toffsetrandomizer_H

    enum {
        Toffsetrandomizer = 1028932,
        OFFSETRANDOMIZER_MODE = 20001,
            OFFSETRANDOMIZER_MODE_OFF = 0,
            OFFSETRANDOMIZER_MODE_NORMAL = 1,
            OFFSETRANDOMIZER_MODE_MASTER = 2,
            OFFSETRANDOMIZER_MODE_SLAVE = 3,
        OFFSETRANDOMIZER_TAGINDEX = 20002,
        OFFSETRANDOMIZER_STARTEXPR = 20003,
        OFFSETRANDOMIZER_NEXTEXPR = 20004,
        OFFSETRANDOMIZER_EXECEXPR = 20005,
        OFFSETRANDOMIZER_SEED = 20006,
        OFFSETRANDOMIZER_INFOTAGSAFFECTED = 20007,

        OFFSETRANDOMIZER_UVWOFFSET_GROUP = 20008,
            OFFSETRANDOMIZER_UVWOFFSET_ENABLED = 20009,
            OFFSETRANDOMIZER_UVWOFFSET_XMIN = 20010,
            OFFSETRANDOMIZER_UVWOFFSET_XMAX = 20011,
            OFFSETRANDOMIZER_UVWOFFSET_YMIN = 20012,
            OFFSETRANDOMIZER_UVWOFFSET_YMAX = 20013,

        OFFSETRANDOMIZER_UVWSCALE_GROUP = 20014,
            OFFSETRANDOMIZER_UVWSCALE_ENABLED = 20015,
            OFFSETRANDOMIZER_UVWSCALE_XMIN = 20016,
            OFFSETRANDOMIZER_UVWSCALE_XMAX = 20017,
            OFFSETRANDOMIZER_UVWSCALE_YMIN = 20018,
            OFFSETRANDOMIZER_UVWSCALE_YMAX = 20019,

        OFFSETRANDOMIZER_OFFSET_GROUP = 20020,
            OFFSETRANDOMIZER_OFFSET_ENABLED = 20021,
            OFFSETRANDOMIZER_OFFSET_MIN = 20022,
            OFFSETRANDOMIZER_OFFSET_MAX = 20023,

        OFFSETRANDOMIZER_SCALE_GROUP = 20024,
            OFFSETRANDOMIZER_SCALE_ENABLED = 20025,
            OFFSETRANDOMIZER_SCALE_MIN = 20026,
            OFFSETRANDOMIZER_SCALE_MAX = 20027,

        OFFSETRANDOMIZER_ROTATION_GROUP = 20028,
            OFFSETRANDOMIZER_ROTATION_ENABLED = 20029,
            OFFSETRANDOMIZER_ROTATION_MIN = 20030,
            OFFSETRANDOMIZER_ROTATION_MAX = 20031,

    };

#endif /* Toffsetrandomizer */

