CONTAINER Toffsetrandomizer {
    NAME Toffsetrandomizer;
    INCLUDE Tbase;

    GROUP ID_TAGPROPERTIES {

        LONG OFFSETRANDOMIZER_MODE { CYCLE {
            OFFSETRANDOMIZER_MODE_OFF;
            OFFSETRANDOMIZER_MODE_NORMAL;
            OFFSETRANDOMIZER_MODE_MASTER;
            OFFSETRANDOMIZER_MODE_SLAVE;
        } DEFAULT OFFSETRANDOMIZER_NORMAL; }
        LONG OFFSETRANDOMIZER_TAGINDEX { MIN 0; CUSTOMGUI LONGSLIDER; MAXSLIDER 10; }
        STRING OFFSETRANDOMIZER_STARTEXPR { }
        STRING OFFSETRANDOMIZER_NEXTEXPR { }
        STRING OFFSETRANDOMIZER_EXECEXPR { }
        LONG OFFSETRANDOMIZER_SEED { MIN 0; DEFAULT 5150; CUSTOMGUI LONGSLIDER; }
        STATICTEXT OFFSETRANDOMIZER_INFOTAGSAFFECTED {}

        GROUP OFFSETRANDOMIZER_UVWOFFSET_GROUP {
            BOOL OFFSETRANDOMIZER_UVWOFFSET_ENABLED { DEFAULT 0; }
            GROUP {
                COLUMNS 2;
                REAL OFFSETRANDOMIZER_UVWOFFSET_XMIN { UNIT PERCENT; DEFAULT 0; }
                REAL OFFSETRANDOMIZER_UVWOFFSET_XMAX { UNIT PERCENT; DEFAULT 100; }
                REAL OFFSETRANDOMIZER_UVWOFFSET_YMIN { UNIT PERCENT; DEFAULT 0; }
                REAL OFFSETRANDOMIZER_UVWOFFSET_YMAX { UNIT PERCENT; DEFAULT 100; }
            }
        }
        GROUP OFFSETRANDOMIZER_UVWSCALE_GROUP {
            BOOL OFFSETRANDOMIZER_UVWSCALE_ENABLED { DEFAULT 0; }
            GROUP {
                COLUMNS 2;
                REAL OFFSETRANDOMIZER_UVWSCALE_XMIN { UNIT PERCENT; DEFAULT 100; }
                REAL OFFSETRANDOMIZER_UVWSCALE_XMAX { UNIT PERCENT; DEFAULT 100; }
                REAL OFFSETRANDOMIZER_UVWSCALE_YMIN { UNIT PERCENT; DEFAULT 100; }
                REAL OFFSETRANDOMIZER_UVWSCALE_YMAX { UNIT PERCENT; DEFAULT 100; }
            }
        }
        GROUP OFFSETRANDOMIZER_OFFSET_GROUP {
            BOOL OFFSETRANDOMIZER_OFFSET_ENABLED { DEFAULT 0; }
            VECTOR OFFSETRANDOMIZER_OFFSET_MIN { UNIT METER; DEFAULT 0 0 0; }
            VECTOR OFFSETRANDOMIZER_OFFSET_MAX { UNIT METER; DEFAULT 0 0 0; }
        }
        GROUP OFFSETRANDOMIZER_SCALE_GROUP {
            BOOL OFFSETRANDOMIZER_SCALE_ENABLED { DEFAULT 0; }
            VECTOR OFFSETRANDOMIZER_SCALE_MIN { UNIT METER; DEFAULT 1 1 1; }
            VECTOR OFFSETRANDOMIZER_SCALE_MAX { UNIT METER; DEFAULT 1 1 1; }
        }
        GROUP OFFSETRANDOMIZER_ROTATION_GROUP {
            BOOL OFFSETRANDOMIZER_ROTATION_ENABLED { DEFAULT 0; }
            VECTOR OFFSETRANDOMIZER_ROTATION_MIN { UNIT DEGREE; DEFAULT 0 0 0; }
            VECTOR OFFSETRANDOMIZER_ROTATION_MAX { UNIT DEGREE; DEFAULT 0 0 0; }
        }
    }

}