// C4D-DialogResource
DIALOG IDS_AUTOCONNECT_DLG_MAIN
{
  NAME IDS_AUTOCONNECT_DLG_MAIN; SCALE_V; SCALE_H;

  GROUP IDC_STATIC
  {
    NAME IDS_STATIC7; ALIGN_TOP; SCALE_H;
    BORDERSIZE 4, 4, 4, 4;
    COLUMNS 1;
    SPACE 4, 4;

    GROUP IDC_STATIC
    {
      NAME IDS_STATIC1; ALIGN_TOP; SCALE_H;
      BORDERSIZE 0, 0, 0, 0;
      COLUMNS 2;
      SPACE 4, 4;

      STATICTEXT IDC_STATIC { NAME IDS_STATIC8; CENTER_V; ALIGN_LEFT; }
      COMBOBOX IDS_AUTOCONNECT_CMB_FORCE
      {
        ALIGN_TOP; SCALE_H; SIZE 150, 0;
        CHILDS
        {
        }
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
      COMBOBOX IDS_AUTOCONNECT_CMB_TYPE
      {
        ALIGN_TOP; SCALE_H; SIZE 150, 0;
        CHILDS
        {
        }
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
      COMBOBOX IDS_AUTOCONNECT_CMB_MODE
      {
        ALIGN_TOP; SCALE_H; SIZE 250, 0;
        CHILDS
        {
          IDS_AUTOCONNECT_CMB_MODE_ALL, IDS_AUTOCONNECT_CMB_MODE_ALL;
          IDS_AUTOCONNECT_CMB_MODE_CHAIN, IDS_AUTOCONNECT_CMB_MODE_CHAIN;
          IDS_AUTOCONNECT_CMB_MODE_NEIGHBOR, IDS_AUTOCONNECT_CMB_MODE_NEIGHBOR;
        }
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC14; CENTER_V; ALIGN_LEFT; }
      EDITSLIDER IDS_AUTOCONNECT_EDT_MAXCONN
      { CENTER_V; SCALE_H; SIZE 70, 0; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
      EDITSLIDER IDS_AUTOCONNECT_EDT_RADIUS
      { CENTER_V; SCALE_H; SIZE 70, 0; }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC12; ALIGN_TOP; ALIGN_LEFT;
        BORDERSIZE 0, 0, 0, 0;
        COLUMNS 1;
        SPACE 4, 4;


      }
      GROUP IDC_STATIC
      {
        NAME IDS_STATIC13; ALIGN_TOP; SCALE_H;
        BORDERSIZE 0, 4, 0, 4;
        ROWS 1;
        SPACE 4, 4;

        GROUP IDC_STATIC
        {
          NAME IDS_STATIC17; ALIGN_TOP; SCALE_H;
          BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0;
          COLUMNS 1;

          CHECKBOX IDS_AUTOCONNECT_CHK_ADDDYNAMICS { NAME IDS_CHECK2; ALIGN_TOP; ALIGN_LEFT;  }
          CHECKBOX IDS_AUTOCONNECT_CHK_COMPOUND { NAME IDS_CHECK1; ALIGN_TOP; ALIGN_LEFT;  }
        }
        CHECKBOX IDS_AUTOCONNECT_CHK_CLOSED { NAME IDS_CHECK; ALIGN_TOP; ALIGN_LEFT;  }
      }
    }
    BUTTON IDS_AUTOCONNECT_BTN_EXECUTE { NAME IDS_BUTTON1; ALIGN_TOP; ALIGN_RIGHT; }
  }
}