#ifndef _C4D_SYMBOLS_H_
#define _C4D_SYMBOLS_H_

enum
{
  __FIRST_ID__ = 10000,

  IDS_MENU_OBJECTS,
  IDS_MENU_SPLINES,
  IDS_MENU_DEFORMERS,
  IDS_MENU_EFFECTORS,

  // Commands
  // --------

  IDS_RESOLVEDUPLICATES_NAME,
  IDS_RESOLVEDUPLICATES_HELP,
  IDS_RESOLVEDUPLICATES_ASKUNDO,
  IDS_RESOLVEDUPLICATES_COLLECTINFO,
  IDS_RESOLVEDUPLICATES_FINDDUPLICATES,

  IDS_EXPLODE_NAME,
  IDS_EXPLODE_HELP,
  IDS_EXPLODE_FINDING_GROUPS,
  IDS_EXPLODE_BUILDING_GEOMETRY,
  IDS_EXPLODE_INSERTING_OBJECTS,

  // Dependency Manager
  // ------------------

  IDC_DEPENDENCYMANAGER_NAME,
  IDC_DEPENDENCYMANAGER_HELP,
  IDC_DEPENDENCYMANAGER_DUPLICATE_TOOLTIP,
  IDC_DEPENDENCYMANAGER_SHOWEMPTY_TOOLTIP,
  IDC_DEPENDENCYTYPE_EFFECTORS,
  IDC_DEPENDENCYTYPE_FORCES,
  IDC_DIALOGMAXREACHED,

  // Dialog
  GRP_MAIN,
  BTN_DUPLICATE,
  BTN_SHOWEMPTY,
  WDG_TREEVIEW,
  MENU_TYPE,
  MENU_TYPE_BASEID = 13500,
  MENU_TYPE_MAXID = 14000,

  // TimeHide
  // --------

  IDC_TIMEHIDE_NAME,

  // Pr1mitives
  // ----------

  IDS_PR1MITIVE_NAME,
  IDS_NETNOTRUNNING,

  IDS_LASTRUN,
  IDS_LASTRUN_MULTI,

  IDS_Opr1m_room,
  IDS_Opr1m_splinechamfer,
  IDS_Opr1m_proxygen,
  IDS_Opr1m_torusknot,
  IDS_Opr1m_pillow,
  IDS_Opr1m_seashell,
  IDS_Opr1m_jet,
  IDS_Opr1m_umbilictorus,
  IDS_Opr1m_spintorus,
  IDS_Opr1m_teardrop,
  IDS_Opr1m_expression,
  IDS_Tpr1m_axisalign,

  // OffsetRandomizer
  // ----------------

  IDC_OFFSETRANDOMIZER,
  IDC_OFFSETRANDOMIZER_TAGSAFFECTED,
  IDC_MESSAGE_REACHEDHIERARCHYEND,
  IDC_MESSAGE_NOTEXTURETAGAT,

  // Smear Deformer
  // --------------

  IDC_SMEARDEFORMER_NAME,
  IDC_SMEARDEFORMER_VERSIONPROBLEM,
  IDC_SMEARING_POSITIONAL,
  IDC_SMEARING_HISTORICAL,
  IDC_WEIGHTING_VERTEXNORMAL,

  // XPresso Effector
  // ----------------

  IDC_CSVEFFECTOR_NAME,
  IDC_CSVNODE_NAME,
  IDC_XPRESSOEFFECTOR_NAME,
  IDC_MODATANODE_NAME,
  IDC_XPE_NAME,
  IDC_POLYSIZEEFFECTOR_NAME,

  IDC_CSVEFFECTOR_STATS_FORMAT,
  IDC_CSVEFFECTOR_STATS_NOFILE,
  IDC_CSVEFFECTOR_STATS_UNKOWNERROR,

  IDC_CSVNODE_FILENAME = 19000,       // Filename [in]
  IDC_CSVNODE_HEADER = 19001,         // Bool   [in]
  IDC_CSVNODE_DELIMITER = 19002,      // LONG   [in]
  IDC_CSVNODE_ROWINDEX = 19003,       // LONG   [in]
  IDC_CSVNODE_LOADED = 19004,         // Bool   [out]
  IDC_CSVNODE_COLCOUNT_TOTAL = 19005, // LONG   [out]
  IDC_CSVNODE_COLCOUNT = 19006,       // LONG   [out]
  IDC_CSVNODE_ROWCOUNT = 19007,       // LONG   [out]

  IDC_CSVNODE_INVALIDPORT,
  IDC_CSVNODE_TABLECOLUMN_PREFIX,
  IDC_CSVNODE_REGISTERED,

  IDC_MODATANODE_PORT_INDEX,
  IDC_MODATANODE_PORT_OBJECT,
  IDC_MODATANODE_PORT_HOST,
  IDC_MODATANODE_PORT_COUNT,
  IDC_MODATANODE_PORT_ITERCOUNT,
  IDC_MODATANODE_PORT_FALLOFF,
  IDC_MODATANODE_PORT_INDEXOUT,
  IDC_MODATANODE_PORT_SELWEIGHT,

  IDC_MODATANODE_PORT_MATRIX,
  IDC_MODATANODE_PORT_COLOR,
  IDC_MODATANODE_PORT_SIZE,
  IDC_MODATANODE_PORT_UVW,
  IDC_MODATANODE_PORT_FLAGS,
  IDC_MODATANODE_PORT_WEIGHT,
  IDC_MODATANODE_PORT_CLONE,
  IDC_MODATANODE_PORT_TIME,
  IDC_MODATANODE_PORT_FALLOFF_WGT,
  IDC_MODATANODE_PORT_SPLINE_SEGMENT,
  IDC_MODATANODE_PORT_GROWTH,
  IDC_MODATANODE_PORT_LASTMAT,
  IDC_MODATANODE_PORT_STARTMAT,
  IDC_MODATANODE_PORT_ALT_INDEX,

  IDC_C4DVERSIONTOOLD,
  IDC_REGISTERED,

  // XGraph
  // ------

  IDS_GVOPERATOR_GRAPH,
  IDS_GVPORT_NAME_REAL,

  // TeaPresso
  // ---------

  IDC_TEAPRESSO,

  IDC_TVROOT,
  IDC_TVCURRENTDOCUMENT,
  IDC_TVCONTAINER,
  IDC_TVEACHDOCUMENT,
  IDC_TVEACHOBJECT,
  IDC_TVEACHTAG,
  IDC_TVCONDITION,
  IDC_TVIF,
  IDC_TVTHEN,
  IDC_TVELSE,
  IDC_TVPRINTCONTEXT,
      IDC_PRINTCONTEXT_NOOBJECT,
  IDC_TVCHECKTYPE,
  IDC_TVISSELECTED,
  IDC_TVPYTHON,
  IDC_TVSELECT,

  IDC_TEXT_INEXPRESSION,
  IDC_TEXT_INCONDITION,

  IDC_TVMANAGER_TITLE,
  IDC_TVMANAGER_OPEN,
  IDC_TVMANAGER_OPEN_HELP,

  IDC_TVPLUGINS_TITLE,
  IDC_TVPLUGINS_OPEN,
  IDC_TVPLUGINS_OPEN_HELP,

  IDC_NODES,
  IDC_OBJECTS,
  IDC_TAGS,
  IDC_SHADERS,
  IDC_MATERIALS,
  IDC_SCENEHOOKS,

  CMG_TREEVIEW,
  BTN_EXECUTE,
  BTN_EDITROOT,

  COLUMN_MAIN,
  COLUMN_ENABLED,
  COLUMN_CUSTOM,

  FOLDER_GENERAL,
  FOLDER_CONDITIONS,
  FOLDER_EXPRESSIONS,
  FOLDER_ITERATORS,
  FOLDER_CONTEXTS,

  CONTEXT_EDIT,
  CONTEXT_PLUGINS,

  // AutoConnect
  // -----------

  IDS_AUTOCONNECT_DLG_MAIN,
  IDS_AUTOCONNECT_CMB_FORCE,
  IDS_AUTOCONNECT_CMB_TYPE,
  IDS_AUTOCONNECT_CMB_MODE,
  IDS_AUTOCONNECT_CMB_MODE_ALL,
  IDS_AUTOCONNECT_CMB_MODE_CHAIN,
  IDS_AUTOCONNECT_CMB_MODE_NEIGHBOR,
  IDS_AUTOCONNECT_EDT_MAXCONN,
  IDS_AUTOCONNECT_EDT_RADIUS,
  IDS_AUTOCONNECT_CHK_ADDDYNAMICS,
  IDS_AUTOCONNECT_CHK_COMPOUND,
  IDS_AUTOCONNECT_CHK_CLOSED,
  IDS_AUTOCONNECT_BTN_EXECUTE,
  IDS_AUTOCONNECT_CMG_DEVLINK,
  IDS_AUTOCONNECT_CMG_DEVLINK_LINK,
  IDS_AUTOCONNECT_NAME,
  IDS_AUTOCONNECT_HELP,
  IDS_AUTOCONNECT_OBJECT,

};

#endif // _C4D_SYMBOLS_H_
