CONTAINER nrprocedural_channel
{
  INCLUDE Obaselist;
  GROUP Obaselist {
    BOOL PROCEDURAL_CHANNEL_UI_TINTENABLED { DEFAULT 0; }
    COLOR PROCEDURAL_CHANNEL_UI_TINTCOLOR { DEFAULT 1 1 1; }
  }
  GROUP PROCEDURAL_CHANNEL_PROPERTIES {
    DEFAULT 1;

    BOOL PROCEDURAL_CHANNEL_PARAM_LOCKED { DEFAULT 0; }
    STRING PROCEDURAL_CHANNEL_PARAM_REF { }

    LONG PROCEDURAL_CHANNEL_PARAM_STATE {
      CYCLE {
        PROCEDURAL_CHANNEL_STATE_UNINITIALIZED;
        PROCEDURAL_CHANNEL_STATE_INITIALIZED;
        PROCEDURAL_CHANNEL_STATE_TYPEERROR;
        PROCEDURAL_CHANNEL_STATE_MEMORYERROR;
        PROCEDURAL_CHANNEL_STATE_REFERROR;
        PROCEDURAL_CHANNEL_STATE_UNKNOWN;
      }
    }

    LONG PROCEDURAL_CHANNEL_PARAM_MODE {
      CYCLE {
        PROCEDURAL_CHANNEL_MODE_FLOATING;
        PROCEDURAL_CHANNEL_MODE_PERMANENT;
      }
      DEFAULT PROCEDURAL_CHANNEL_MODE_FLOATING;
    }

    LONG PROCEDURAL_CHANNEL_PARAM_TYPE {
      CYCLE {
        PROCEDURAL_CHANNEL_TYPE_NIL;
        PROCEDURAL_CHANNEL_TYPE_INTEGER;
        PROCEDURAL_CHANNEL_TYPE_FLOAT;
        PROCEDURAL_CHANNEL_TYPE_VECTOR;
        PROCEDURAL_CHANNEL_TYPE_MATRIX;
        PROCEDURAL_CHANNEL_TYPE_STRING;
      }
      DEFAULT PROCEDURAL_CHANNEL_TYPE_FLOAT;
    }

    LONG PROCEDURAL_CHANNEL_PARAM_COUNT { MIN 0; }
    LONG PROCEDURAL_CHANNEL_PARAM_ITEMLENGTH { MIN 1; MAX 16; }

    LONG PROCEDURAL_CHANNEL_PARAM_FRAMECOUNT { MIN 1; DEFAULT 1; }
    LONG PROCEDURAL_CHANNEL_PARAM_FRAME { MIN 0; DEFAULT 0; }
    BOOL PROCEDURAL_CHANNEL_PARAM_SYNCFRAME { DEFAULT 1; }
    LONG PROCEDURAL_CHANNEL_PARAM_FRAMEOFFSET { DEFAULT 0; }

    SEPARATOR { LINE; }

    LONG PROCEDURAL_CHANNEL_PARAM_DEFAULTV_INTEGER { }
    REAL PROCEDURAL_CHANNEL_PARAM_DEFAULTV_FLOAT { }
    VECTOR PROCEDURAL_CHANNEL_PARAM_DEFAULTV_VECTOR { }
    MATRIX PROCEDURAL_CHANNEL_PARAM_DEFAULTV_MATRIX { }
    STRING PROCEDURAL_CHANNEL_PARAM_DEFAULTV_STRING { }
    SEPARATOR { LINE; }

    GROUP {
      COLUMNS 2;
      BUTTON PROCEDURAL_CHANNEL_UI_MANUALREINIT { }
      BUTTON PROCEDURAL_CHANNEL_UI_GOTOREF { }
    }
    STRING PROCEDURAL_CHANNEL_UI_MEMINFO { CUSTOMGUI STATICTEXT; }
  }
  GROUP PROCEDURAL_CHANNEL_GROUP_DISPLAY {
    LONG PROCEDURAL_CHANNEL_DISPLAY_MODE {
      CYCLE {
        PROCEDURAL_CHANNEL_DISPLAY_MODE_OFF;
        PROCEDURAL_CHANNEL_DISPLAY_MODE_LOCAL;
        PROCEDURAL_CHANNEL_DISPLAY_MODE_GLOBAL;
        PROCEDURAL_CHANNEL_DISPLAY_MODE_REFTEXT;
        PROCEDURAL_CHANNEL_DISPLAY_MODE_REFVIS;
      }
      DEFAULT PROCEDURAL_CHANNEL_DISPLAY_MODE_OFF;
    }
    GROUP PROCEDURAL_CHANNEL_GROUP_DISPLAY_COLORS {
      COLUMNS 2;
      // Automatically generated parameters follow.
    }
  }
}
