CONTAINER Ocsveffector {
    NAME        Ocsveffector;
    INCLUDE     Obaseeffector;

    HIDE ID_MG_BASEEFFECTOR_GROUPTRANSFORM;
    HIDE ID_MG_BASEEFFECTOR_GROUPCOLOR;
    HIDE ID_MG_BASEEFFECTOR_GROUPOTHER;

    GROUP ID_MG_BASEEFFECTOR_GROUPEFFECTOR {
        DEFAULT 1;

        GROUP {
            FILENAME CSVEFFECTOR_FILENAME { ANIM OFF; SCALE_H; }
            LONG CSVEFFECTOR_DELIMITER {
                DEFAULT CSVEFFECTOR_DELIMITER_COMMA;
                ANIM OFF;
                CYCLE {
                    CSVEFFECTOR_DELIMITER_COMMA;
                    CSVEFFECTOR_DELIMITER_SEMICOLON;
                    CSVEFFECTOR_DELIMITER_TAB;
                }
                SCALE_H;
            }
            GROUP {
                COLUMNS 3;
                BOOL CSVEFFECTOR_HASHEADER { DEFAULT 1; ANIM OFF; }
                STATICTEXT CSVEFFECTOR_STATS { SCALE_H; }
                BUTTON CSVEFFECTOR_FORCERELOAD { }
            }
        }
    }
    GROUP ID_MG_BASEEFFECTOR_GROUPPARAMETER {

        BOOL CSVEFFECTOR_REPEAT { DEFAULT 1; }
        LONG CSVEFFECTOR_OFFSET { CUSTOMGUI LONGSLIDER; MINSLIDER 0; MAXSLIDER 50; DEFAULT 0; }
        LONG CSVEFFECTOR_ANGLEMODE { CYCLE {
            CSVEFFECTOR_ANGLEMODE_DEGREES;
            CSVEFFECTOR_ANGLEMODE_RADIANS;
        }}

        SEPARATOR CSVEFFECTOR_ASSIGNMENT { }

        GROUP {
            DEFAULT 1;
            COLUMNS 3;

            LONG CSVEFFECTOR_ASSIGNMENT_XPOS { CYCLE {}; DEFAULT -1; }
            LONG CSVEFFECTOR_ASSIGNMENT_XSCALE { CYCLE {}; DEFAULT -1; }
            LONG CSVEFFECTOR_ASSIGNMENT_XROT { CYCLE {}; DEFAULT -1; }

            LONG CSVEFFECTOR_ASSIGNMENT_YPOS { CYCLE {}; DEFAULT -1; }
            LONG CSVEFFECTOR_ASSIGNMENT_YSCALE { CYCLE {}; DEFAULT -1; }
            LONG CSVEFFECTOR_ASSIGNMENT_YROT { CYCLE {}; DEFAULT -1; }

            LONG CSVEFFECTOR_ASSIGNMENT_ZPOS { CYCLE {}; DEFAULT -1; }
            LONG CSVEFFECTOR_ASSIGNMENT_ZSCALE { CYCLE {}; DEFAULT -1; }
            LONG CSVEFFECTOR_ASSIGNMENT_ZROT { CYCLE {}; DEFAULT -1; }
        }

        SEPARATOR CSVEFFECTOR_MULTIPLIER { }

        GROUP {
            VECTOR CSVEFFECTOR_MULTIPLIER_POS { DEFAULT 1 1 1; UNIT PERCENT; }
            VECTOR CSVEFFECTOR_MULTIPLIER_SCALE { DEFAULT 1 1 1; UNIT PERCENT; }
            VECTOR CSVEFFECTOR_MULTIPLIER_ROT { DEFAULT 1 1 1; UNIT PERCENT; }
        }
    }
}
