CONTAINER Opr1m_expression {
    NAME Opr1m_expression;
    INCLUDE Obase;

    GROUP ID_OBJECTPROPERTIES {
        STRING PR1M_EXPRESSIONSHAPE_XEXPR {}
        STRING PR1M_EXPRESSIONSHAPE_YEXPR {}
        STRING PR1M_EXPRESSIONSHAPE_ZEXPR {}

        GROUP {
            COLUMNS 2;
            REAL PR1M_EXPRESSIONSHAPE_UMIN { STEP 0.01; }
            REAL PR1M_EXPRESSIONSHAPE_UMAX { STEP 0.01; }
            REAL PR1M_EXPRESSIONSHAPE_VMIN { STEP 0.01; }
            REAL PR1M_EXPRESSIONSHAPE_VMAX { STEP 0.01; }
        }

        GROUP {
            COLUMNS 2;
            BOOL PR1M_EXPRESSIONSHAPE_INVERSENORMALS { DEFAULT 0; }
            BOOL PR1M_EXPRESSIONSHAPE_ROTATEPOLYGONS { DEFAULT 0; }
            BOOL PR1M_EXPRESSIONSHAPE_FLIPUVWX { DEFAULT 0; }
            BOOL PR1M_EXPRESSIONSHAPE_FLIPUVWY { DEFAULT 0; }
        }

        SEPARATOR { LINE; }

    }

    INCLUDE Opr1m_complexshape;
}