CONTAINER Opr1m_proxygen {
    NAME Opr1m_proxygen;
    INCLUDE Obase;

    GROUP ID_OBJECTPROPERTIES {
        BOOL PR1M_PROXYGEN_DETAILED { DEFAULT 1; }
        BOOL PR1M_PROXYGEN_HIERARCHY { DEFAULT 1; }
        IN_EXCLUDE PR1M_PROXYGEN_OBJECTS { ACCEPT { Obase; } }
    }
}