CONTAINER Shistorical {
    INCLUDE Sbase;

    GROUP ID_SMEARINGENGINE_PROPERTIES {
        REAL SHISTORICAL_TIMEDELTA { CUSTOMGUI REALSLIDER; MIN 0; MINSLIDER 0; MAXSLIDER 1; STEP 0.01; DEFAULT 0.1; }
    }
}