CONTAINER Gvcsv {
    NAME Gvcsv;
    INCLUDE Gvbase;

    GROUP ID_GVPROPERTIES {
        BOOL CSVNODE_FORCEOUTPORTS { }
        LONG CSVNODE_FORCEOUTPORTS_COUNT { MIN 0; CUSTOMGUI LONGSLIDER; MINSLIDER 0; MAXSLIDER 15; }
    }

    GROUP ID_GVPORTS {
        FILENAME CSVNODE_FILENAME  { INPORT; }
        BOOL     CSVNODE_HEADER    { INPORT; DEFAULT 0; }
        LONG     CSVNODE_DELIMITER { INPORT; DEFAULT CSVNODE_DELIMITER_COMMA;
            CYCLE {
                CSVNODE_DELIMITER_COMMA;
                CSVNODE_DELIMITER_SEMICOLON;
                CSVNODE_DELIMITER_TAB;
            }
        }
        LONG CSVNODE_ROWINDEX { INPORT; DEFAULT 0; }
    }
}