/// Copyright (C) 2015, Niklas Rosenstein
/// All rights reserved.
///
/// \file res/description/nrprocedural_csvreader.h
/// \lastmodified 2015/05/29

#ifndef NRPROCEDURAL_CSVREADER_H_
#define NRPROCEDURAL_CSVREADER_H_

enum
{
  PROCEDURAL_CSVREADER_ID         = 1035300,
  PROCEDURAL_CSVREADER_GROUP      = 4008,
  PROCEDURAL_CSVREADER_STATUS     = 4005,
  PROCEDURAL_CSVREADER_ENABLED    = 4007,
  PROCEDURAL_CSVREADER_PRIORITY   = 4006,
  PROCEDURAL_CSVREADER_HASHEADER  = 4001,
  PROCEDURAL_CSVREADER_FILENAME   = 4000,
  PROCEDURAL_CSVREADER_ANIMATED   = 4009,
  PROCEDURAL_CSVREADER_ANIMSTATUS = 4010,
  PROCEDURAL_CSVREADER_ANIMCACHED = 4011,
  PROCEDURAL_CSVREADER_ANIMOFFSET = 4012,
  PROCEDURAL_CSVREADER_ADDENTRY   = 4002,
  PROCEDURAL_CSVREADER_SUBENTRY   = 4003,
  PROCEDURAL_CSVREADER_ENTRYCOUNT = 4004,

  PROCEDURAL_CSVREADER_MAXENTRIES = 32,
  PROCEDURAL_CSVREADER_ENTRYMINID = 5000,
  PROCEDURAL_CSVREADER_ENTRYSIZE  = 512,
  PROCEDURAL_CSVREADER_ENTRYMAXID = 13191,

    PROCEDURAL_CSVREADER_ENTRY_GROUP = 0,
    PROCEDURAL_CSVREADER_ENTRY_CHANNELNAME = 1,
    PROCEDURAL_CSVREADER_ENTRY_LASTDIRTYCOUNT = 2,
    PROCEDURAL_CSVREADER_ENTRY_COLUMNSTART = 4,
};

#endif // NRPROCEDURAL_CSVREADER_H_
