CONTAINER Osmeardeformer {
    NAME Osmeardeformer;
    INCLUDE Obase;
    INCLUDE Wbase;
    INCLUDE Sbase;

    GROUP ID_OBJECTPROPERTIES {
        DEFAULT 1;
        BOOL SMEARDEFORMER_INTERACTIVE { DEFAULT 0; }
        REAL SMEARDEFORMER_STRENGTH { UNIT PERCENT; CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 100; }
    }
    GROUP ID_WEIGHTINGENGINE_PROPERTIES {
        DEFAULT 1;
        GROUP {
            LONG SMEARDEFORMER_WEIGHTINGENGINE { CYCLE { } }
        }
        BOOL SMEARDEFORMER_WEIGHTINGINVERSE { DEFAULT 0; }

        SEPARATOR { LINE; }

        BOOL SMEARDEFORMER_WEIGHTINGUSEPLINE { DEFAULT 0; }
        SPLINE SMEARDEFORMER_WEIGHTINGSPLINE { }

        SEPARATOR { LINE; }

        BOOL SMEARDEFORMER_EASEWEIGHT { DEFAULT 1; }
        SPLINE SMEARDEFORMER_EASEWEIGHTSPLINE { }

        SEPARATOR { LINE; }
    }
    GROUP ID_SMEARINGENGINE_PROPERTIES {
        DEFAULT 1;
        GROUP {
            LONG SMEARDEFORMER_SMEARINGENGINE { CYCLE { } }
        }
    }
}