CONTAINER Oxpressoeffector {
    NAME Oxpressoeffector;
    INCLUDE Obaseeffector;

    GROUP ID_MG_BASEEFFECTOR_GROUPEFFECTOR {
        BOOL XPRESSOEFFECTOR_TIMEDEPENDENT { DEFAULT 0; }
        IN_EXCLUDE XPRESSOEFFECTOR_DEPENDENCIES { }
    }

}