// coding: ansii
//
// Copyright (C) 2012-2013, Niklas Rosenstein
// All rights reserved.

CONTAINER Tpr1m_axisalign {
    NAME Tpr1m_axisalign;
    INCLUDE Tbase;
    INCLUDE Texpression;

    GROUP ID_TAGPROPERTIES {
        BOOL PR1M_ALIGNMENT_ENABLED { DEFAULT 0; }

        REAL PR1M_ALIGNMENT_X { UNIT PERCENT; DEFAULT 0; CUSTOMGUI REALSLIDER; MINSLIDER -100; MAXSLIDER 100; }
        REAL PR1M_ALIGNMENT_Y { UNIT PERCENT; DEFAULT 0; CUSTOMGUI REALSLIDER; MINSLIDER -100; MAXSLIDER 100; }
        REAL PR1M_ALIGNMENT_Z { UNIT PERCENT; DEFAULT 0; CUSTOMGUI REALSLIDER; MINSLIDER -100; MAXSLIDER 100; }

        VECTOR PR1M_ALIGNMENT_OFF { UNIT METER; DEFAULT 0 0 0; }
        VECTOR PR1M_ALIGNMENT_OFFMUL { UNIT PERCENT; DEFAULT 0 0 0; }
        BOOL   PR1M_ALIGNMENT_INVERSEOFF { DEFAULT 0; }

        SEPARATOR { LINE; }

        BOOL PR1M_ALIGNMENT_USECACHE { DEFAULT 0; }
        BOOL PR1M_ALIGNMENT_INCLUDEHIERARCHY { DEFAULT 0; }

        LINK PR1M_ALIGNMENT_INDICATOR { ACCEPT { Obase; } }

    }

}
